export const urlService = {
  api: '/api',
  login: '/login',
  sales: '/sales',
  master: '/master',
  product: '/product',
  kubotauser: '/kubotauser',
  getMachineItemNo: '/getMachineItemNo',
  salesandpresales: '/salesandpresales',
  getSystemGeneratedDate: '/getSystemGeneratedDate',
  reports : '/reports',

  //****Quotation */
  Quotation: '/Quotation',
  getMachineDetailByItemNo: '/getMachineDetailByItemNo',
  addQuotation: '/addQuotation',
  printQuotation: '/getQuotationPrint',
  getQuotationSearch: '/getQuotationSearch',
  getQuotationCode: '/getQuotationCode',
  getQuotationByQuotationNumber: '/getQuotationByQuotationNumber',
  getItemInMachineTransfer: '/getItemInMachineTransfer',
  searchMachineTransferRequest: '/searchMachineTransferRequest',
  findByRequestNumber: '/findByRequestNumber',
  budgetTypeDropdown: '/budgetTypeDropdown',
  getItemNumberModelProductSeries: '/getItemNumberModelProductSeries',
  saveactivitytypebudgetmaster: '/saveactivitytypebudgetmaster',
  getAutoCompleteOpenEnquiryForQuotation: '/getAutoCompleteOpenEnquiryForQuotation',

  //-----enquiry----------//
  enquiry: '/enquiry',
  reopenEnquiry: '/reopenEnquiry',
  getEnquiryCode: '/getEnquiryCode',
  getEnquiryNo: '/getEnquiryNo',
  getSeriesByProduct: '/getSeriesByProduct',
  getModelBySeries: '/getModelBySeries',
  enquirySource: '/enquirySource',
  getSource: '/getSource',
  getFollowUpType: '/getFollowUpType',
  getRetailConversionActivityType: '/getRetailConversionActivityType',
  getItemNo: '/getByItemNo',
  machineMaster: '/machineMaster',
  autoCompleteItems: '/autoCompleteItems',
  getByItemNo: '/getByItemNo',
  getBrands: '/getBrands',
  getPurposeOfPurchase: '/getPurposeOfPurchase',
  getGenerationActivityType: '/getGenerationActivityType',
  getConversionActivityType: '/getConversionActivityType',
  getEnquiry: '/getEnquiry',
  addEnquiry: '/addEnquiry',
  getExchangeBrand: '/getExchangeBrand',
  getByIteenquirysourcemNo: '/getByItemNo',
  getModel: '/getModel',
  getSubModel: '/getSubModel',
  getVariant: '/getVariant',
  itemMaster: '/itemMaster',
  getOccupation: '/getOccupation',
  searchRequestNumber: '/searchRequestNumber',
  getSoilType: '/getSoilType',
  getMajorCropGrown: '/getMajorCropGrown',
  getProspectType: '/getProspectType',
  getMobileNumber: '/getMobileNumber',
  getDataByMobileNo: '/getDataByMobileNo',
  getPinCode: '/getPinCode',
  getByPinCode: '/getByPinCode',
  getPostOffice: '/getPostOffice',
  areaMaster: '/areamaster',
  getCashLoan: '/getCashLoan',
  getFinalStatus: '/getFinalStatus',
  getEnquiryById: '/getEnquiryById',
  getEnquiryByEnquiryNumber: '/getEnquiryByEnquiryNumber',
  getSeriesAndProductByModel: '/getSeriesAndProductByModel',
  setEnquiryType: '/setEnquiryType',
  searchMarketingActivityNumber: '/searchMarketingActivityNumber',
  getItemByModelSubModelVariant: '/getItemByModelSubModelVariant',
  getEnquiryNumberNameMobileNoTehsil: '/getEnquiryNumberNameMobileNoTehsil',
  updateEnquiry: '/updateEnquiry',
  getItemByModel: '/getItemByModel',
  getDealerCodeAndDealerNameAndGstNo: '/getDealerCodeAndDealerNameAndGstNo',
  //search enquiry
  getAllModel: '/getAllModel',
  getAllSubModel: '/getAllSubModel',
  getAllProduct: '/getAllProduct',
  getAllVariant: '/getAllVariant',
  getAllSeries: '/getAllSeries',
  getEnquirySearch: '/getEnquirySearch',
  getEnquiryStatus: '/getEnquiryStatus',
  searchProspectCode: '/searchProspectCode',
  searchProspectMasterByProspectCode: '/searchProspectMasterByProspectCode',
  //enquiry follow up
  enquiryFollowUp: '/enquiryFollowUp',
  getEnquiryFollowByEnquiryCode: '/getEnquiryFollowByEnquiryCode',
  addEnquiryFollowUp: '/addEnquiryFollowUp',
  getResult: '/getResult',
  getLostDropReason: '/getLostDropReason',
  getReason: '/getReason',
  enquiryNumber: '/enquiryNumber',
  searchEmployeeName: '/searchEmployeeName',
  getMachineTransferStatus: '/getMachineTransferStatus',
  getFollowUpHistory: '/getFollowUpHistory',
  getEnquiryPrint: '/getEnquiryPrint',
  // addEnquiryLostDrop: '/addEnquiryLostDrop',

  // Trnasfer Enquiry //
  getAllTehsil: '/getAllTehsil',
  dealerEmployeeMaster: '/dealerEmployeeMaster',
  getDealerCodes: '/getDealerCodes',
  getSalesPerson: '/getSalesPerson',
  getEnquiryToTransfer: '/getEnquiryToTransfer',
  searchCoDealer: '/searchCoDealer',
  addTransfer: '/addTransfer',
  addEnquiryLostDrop: '/addEnquiryLostDrop',
  getenquirybyactivitynumber: '/getenquirybyactivitynumber',
  searchActivityBudgetMaster: '/searchActivityBudgetMaster',
  getEnquiryByEnquiryNo: '/getEnquiryByEnquiryNo',
  getSalesPersonNameInTransfer: '/getSalesPersonNameInTransfer',
  //getEnquiryCode: '/getEnquiryCode',

  // ************* ACCPAC ***************,
  accpac: '/accpac',
  getOsStatus: '/getOsStatus',

  // ************* Purchase Order ***************,
  getDealerAvailableCreditByDealerCode: '/getDealerAvailableCreditByDealerCode',
  getDealerBankDetailsByBankAndDealer: '/getDealerBankDetailsByBankAndDealer',
  getChannelFinanceAvailable: '/getChannelFinanceAvailable',
  getpurchaseorder: '/getpurchaseorder',
  approvePurchaseOrder: '/approvePurchaseOrder',
  printpourl:'/printPurchaseOrder',
  purchaseOrderStatus: '/purchaseOrderStatus',
  getBankListByDealer: '/getBankListByDealer',
  purchaseOrderType: '/purchaseOrderType',
  dealerbankdetails: '/dealerbankdetails',
  savePurchaseOrder: '/savePurchaseOrder',
  // Bulk Approval Api
  getPoPendingForApproval:'/getPoPendingForApproval',
  getPoDiscountType: '/getPoDiscountType',
  searchPoNumber: '/searchPoNumber',
  purchaseOrder: '/purchaseOrder',
  getBankList: '/getBankList',
  depot: '/depot',
  getSalesPoApprovalDetails: '/getSalesPoApprovalDetails',
  getTcsPercList: '/tcsPercList',
  getTcsPercentageList: '/getDealerTcsValue',
  downloadPoExcelReport:'/downloadPoExcelReport',
  // Channel Finance Indent


  //descripancy claim
  purchase: '/purchase',
  machineDescripancyClaim: '/machineDescripancyClaim',
  getDiscrepancyComplaints: '/getDiscrepancyComplaints',
  saveDiscrepancyClaim: '/saveDiscrepancyClaim',
  // searchClaimNumber: '/searchClaimNumber',
  getClaimStatus: '/getClaimStatus',
  getDetailsByClaimId: '/getDetailsByClaimId',

  //*******Marketing Activity Proposal,
  enquirysource: '/enquirysource',
  getPurpose: '/getPurpose',
  saveMarketingActivityProposal: '/saveMarketingActivityProposal',
  searchactivitytype: '/searchactivitytype',
  marketingActivityStatus: '/marketingActivityStatus',
  marketingActivityProposal: '/marketingActivityProposal',
  searchActivityNumber: '/searchActivityNumber',
  activitytypebudgetmaster: '/activitytypebudgetmaster',
  getmaximumlimitbyactivitytype: '/getmaximumlimitbyactivitytype',
  getEnquiryForActivityPurpose: '/getEnquiryForActivityPurpose',
  searchEnquiryForProposal: '/searchEnquiryForProposal',
  getEnquiryByNumber: '/getEnquiryByNumber',
  getActivityTypeByPurpose: '/getActivityTypeByPurpose',
  approveMarketingActivityProposal: '/approveMarketingActivityProposal',
  getActivityCategory:'/getActivityCategory',
  dealerCodeUrl : '/getDealerCodeAutoComplete',
  
  orgLevelByHODeptUrl : '/getOrgLevelByHODept',
  orgLevelHierForParentUrl : '/getOrgLevelHierForParent',
 
  updateGracePeriodUrl: '/updateGracePeriod',

  //******************Marketing activity claim */
  marketingActivityClaim: '/marketingActivityClaim',
  getReportImagesByProposalId:'/getReportImagesByProposalId',
  searchActivityNumberForClaim: '/searchActivityNumberForClaim',
  getDetailsByActivityNumber: '/getDetailsByActivityNumber',
  staticPath: '/files',
  searchClaimNumber: '/searchClaimNumber',
  searchClaimStatus: '/searchClaimStatus',
  getActivityTypes: '/getActivityTypes',
  getActivityEffectiveness: '/getActivityEffectiveness',
  getClaimById: '/getClaimById',
  addDealerMachineTransfer: '/addDealerMachineTransfer',
  maximumLimitAuto: '/maximumLimitAuto',
  maximumDayMonthAuto: '/maximumDayMonthAuto',
  kaiShareAuto: '/kaiShareAuto',
  saveClaim: '/saveClaim',
  approveMarketingActivityClaim: '/approveMarketingActivityClaim',
  marketingActivityClaimPendingForApproval: '/getClaimsPendingForApproval',
  marketingActivityProposalPendingForApproval: '/getProposalsPendingForApproval',
  // /api/files/


  //*******Marketing Activity Report Create,
  proposaldetailsbyactivitynumber: '/proposaldetailsbyactivitynumber',
  marketingactivityreport: '/marketingactivityreport',
  savereport: '/savereport',
  activityReportById: '/activityReportById',
  activityProposalById: '/activityProposalById',
  searchBy: '/searchBy',
  getEnquiryByActivityNumber: '/getEnquiryByActivityNumber',
  searchActivityNumberForReport: '/searchActivityNumberForReport',
  editMarketingActivityClaim:'/editMarketingActivityClaim',

  // **********Payment Receipt
  getBank: '/getBank',
  getCardType: '/getCardType',
  paymentReceipt: '/paymentReceipt',
  getReceiptType: '/getReceiptType',
  getAllReceiptType:'/getAllReceiptType',
  getReceiptMode: '/getReceiptMode',
  getCheckDdBank: '/getCheckDdBank',
  getEnquiryPayment: '/getEnquiryPayment',
  searchByCustomerName: '/searchByCustomerName',
  searchByMobileNumber: '/searchByMobileNumber',
  searchByReceiptNumber: '/searchByReceiptNumber',
  getPaymentReceiptByReceiptNumber: '/getPaymentReceiptByReceiptNumber',
  getTrasnferFromDealerCode: '/getTrasnferFromDealerCode',


  //*****Update Vehicle Registration No.******/
  customerMaster: '/customerMaster',
  chassisNoAuto: '/chassisNoAuto',
  getDetailsByChassisNo: '/getDetailsByChassisNo',
  customerCodeAuto: '/customerCodeAuto',
  getSalesSearch: '/getSalesSearch',
  addSales: '/addSales',
  //*************Quotation/

  addPayment: '/addPayment',
  getExchangeAmount: '/getExchangeAmount',
  getLoanAmount: '/getLoanAmount',
  getMarginAmount: '/getMarginAmount',
  getSubsidyAmount: '/getSubsidyAmount',
  getPaymentReceiptList: '/getPaymentReceiptList',
  getReceiptNumber: '/getReceiptNumber',
  getPaymentReceiptById: '/getPaymentReceiptById',
  getPaymentReceiptPrint:'/getPaymentReceiptPrint',
  //  incentive scheme master //
  incentiveScheme: '/incentiveScheme',
  schemeTypeDropdown: '/schemeTypeDropdown',
  zoneRegion: '/zoneRegion',
  getAllZones: '/getAllZones',
  getRegionByZoneId: '/getRegionByZoneId',
  getAreaByRegionId: '/getAreaByRegionId',
  getTerritoryByAreaId: '/getTerritoryByAreaId',
  getSchemeDate: '/getSchemeDate',
  seriesDropdown: '/seriesDropdown',
  modelDropdown: '/modelDropdown',
  subModelDropdown: '/subModelDropdown',
  variantDropdown: '/variantDropdown',

  /* ----------- Goods Receipt Note ---------- */
  grn: '/grn',
  createMachineGrn: '/createMachineGrn',
  getGrnType: '/getGrnType',
  getTransporterName: '/getTransporterName',
  searchAccPacInvoiceNumber: '/searchAccPacInvoiceNumber',
  searchAccPacInvoiceByInvoiceNumber: '/searchAccPacInvoiceByInvoiceNumber',
  getGrnByDmsGrnNumber: '/getGrnByDmsGrnNumber',
  printGrnUrl:'/getGrnPrint',
  searchGrn: '/searchGrn',
  searchByDmsGrnNumber: '/searchByDmsGrnNumber',
  getGrnStatus: '/getGrnStatus',
  searchGrnInvoiceNumber: '/searchGrnInvoiceNumber',

  // ***************** Channel Finance Indent *****************
  saveInvoiceData: '/saveInvoiceData',
  getChannelFinanceIndentById: '/getChannelFinanceIndentById',
  saveChannelFinanceIndent: '/saveChannelFinanceIndent',
  channelFinanceIndent: '/channelFinanceIndent',
  searchIndentNumber: '/searchIndentNumber',
  getDealerCategory: '/getDealerCategory',
  getInvoices: '/getInvoices',
  printIndentUrl : '/getChanneFinlIndentPrint',

  // ******************* Delivery Challan ************************
  getMachineAndDealerDetailsByRequestNumber: '/getMachineAndDealerDetailsByRequestNumber',
  getDeliveryChallanNumberAutoComplete: '/getDeliveryChallanNumberAutoComplete',
  getDcCustomerMobileNumberAutoComplete: '/getDcCustomerMobileNumberAutoComplete',
  getMachineDetailsByEnquiryNumber: '/getMachineDetailsByEnquiryNumber',
  getDcChassisNumberAutoComplete: '/getDcChassisNumberAutoComplete',
  dcDownloadExcelReport: '/dcDownloadExcelReport',
  getDcRequestNumberAutoComplete: '/getDcRequestNumberAutoComplete',
  getDcEnquiryNumberAutoComplete: '/getDcEnquiryNumberAutoComplete',
  getDcCustomerNameAutoComplete: '/getDcCustomerNameAutoComplete',
  getDcEngineNumberAutoComplete: '/getDcEngineNumberAutoComplete',
  getInsuranceCodeAutoComplete: '/getInsuranceCodeAutoComplete',
  getDcCancellationOtherReason: '/getDcCancellationOtherReason',
  getEnquiryNumberAutoComplete: '/getEnquiryNumberAutoComplete',
  allotmentNumberAutoComplete: '/allotmentNumberAutoComplete',
  getItemDetailsByItemNumber: '/getItemDetailsByItemNumber',
  getInsuranceDetailsByCode: '/getInsuranceDetailsByCode',
  getItemNumberAutoComplete: '/getItemNumberAutoComplete',
  getDcCancellationReason: '/getDcCancellationReason',
  getDeliveryChallanType: '/getDeliveryChallanType',
  getDcCancellationType: '/getDcCancellationType',
  getDcStatusDropDown: '/getDcStatusDropDown',
  addDeliveryChallan: '/addDeliveryChallan',
  allotmentDetails: '/allotmentDetails',
  deliveryChallan: '/deliveryChallan',
  deliveryChallanCancellationApproval: '/dcListForApproval',
  getEnquiryType: '/getEnquiryType',
  getDcById: '/getDcById',
  approveDc: '/approveDc',
  dcSearch: '/dcSearch',
  dcCancel: '/dcCancel',
  printGatepass : '/getGatePassPrint',
  printDc: '/getDeliveryChallanPrint',

  /* ----------- allotment/deallotment ------------ */
  searchMachineByChassisNumber: '/searchMachineByChassisNumber',
  searchMachineChassisNumber: '/searchMachineChassisNumber',
  searchImplementsMachineChassisNumber: '/searchImplementsMachineChassisNumber',
  getEnquiryMachineDetailByEnquiryNumber: '/getEnquiryMachineDetailByEnquiryNumber',
  getAllotmentNumber: '/getAllotmentNumber',
  getAllotmentByAllotmentNumber: '/getAllotmentByAllotmentNumber',
  // deAllotImplements: '/deAllotImplements',
  // addAllotment: '/addAllotment',
  // getEnquiryInAllotment: '/getEnquiryInAllotment',
  getAllotmentById: '/getAllotmentById',
  machineAllotment: '/machineAllotment',
  getCustomer: '/getCustomer',
  autoCompleteChassisNo: '/autoCompleteChassisNo',
  autoCompleteImplementItemNo: '/autoCompleteImplementItemNo',
  searchByEnquiryNumberForAllotment: '/searchByEnquiryNumberForAllotment',
  searchByAllotmentNumber: '/searchByAllotmentNumber',
  searchMachineAllotment: '/searchMachineAllotment',
  searchByEngineNumber: '/searchByEngineNumber',
  getEnquiryMachineDetailByEnquiryId: '/getEnquiryMachineDetailByEnquiryId',
  deAllotMainMachine: '/deAllotMainMachine',
  deAllotMachineImplements: '/deAllotMachineImplements',
  searchByEnquiryNumber: '/searchByEnquiryNumber',

  /* ----------- Kubota User ----------- */
  getFunctionalityMappedToUser: '/getFunctionalityMappedToUser',
  checkRouterAccessibility: '/checkRouterAccessibility',

  /*----------------------Machine Descripancy Complaint--------------*/
  machineDescripancyComplaint: '/machineDescripancyComplaint',

  searchChassisNumber: '/searchChassisNumber',
  getDetailsByChassisNumber: '/getDetailsByChassisNumber',
  searchItemNumber: '/searchItemNumber',
  searchComplaintNumber: '/searchComplaintNumber',
  searchGrnNumber: '/searchGrnNumber',
  searchExistingChassisNumber: '/searchExistingChassisNumber',
  getComplaintStatus: '/getComplaintStatus',
  getDetailsByItemId: '/getDetailsByItemId',
  saveMachineDescripancyComplaint: '/saveMachineDescripancyComplaint',
  getComplaintType: '/getComplaintType',
  getMachineDescripancyComplaintById: '/getMachineDescripancyComplaintById',

  /****************** item master******************/
  getProduct: '/getProduct',
  itemNoAuto: '/itemNoAuto',
  searchItem: '/searchItem',
  /****** department master ******/
  department: '/department',
  searchDepartment: '/searchDepartment',
  searchByDepartmentCode: '/searchByDepartmentCode',
  departmentNameDropdown: '/departmentNameDropdown',
  linkedToDealerDropdown: '/linkedToDealerDropdown',
  dealerCodeDropdown: '/dealerCodeDropdown',
  changeActiveStatus: '/changeActiveStatus',

  /******designation master*******/
  designation: '/designation',
  searchByDesignation: '/searchByDesignation',
  getHierarchy: '/getHierarchy',
  searchDesignation: '/searchDesignation',

  /*****Kubota Employee ******/
  kubotaemployee: '/kubotaemployee',
  employeeCodeAuto: '/employeeCodeAuto',
  employeeNameAuto: '/employeeNameAuto',
  designationLevelAuto: '/designationLevelAuto',
  getZonalManagers: '/getZonalManagers',
  getRegionalManagers: '/getRegionalManagers',
  getEmployeeNameByEmployeeCode: '/getEmployeeNameByEmployeeCode',
  designationLevel: '/designationLevel',
  getActiveKaiBranch: '/getActiveKaiBranch',
  searchEmployee: '/searchEmployee',

  /* ------------ invoice ----------- */
  invoice: '/invoice',
  printInvoice: '/getInvoicePrint',
  getCustomerCodeAutoComplete: '/getCustomerCodeAutoComplete',
  getDcAndCustomerDetailsByCustomerCode: '/getDcAndCustomerDetailsByCustomerCode',
  getMaterialDetailsByDcId: '/getMaterialDetailsByDcId',
  getGstValue: '/getGstValue',
  getInvoiceType: '/getInvoiceType',
  getInvoiceStatus: '/getInvoiceStatus',
  getBankName: '/getBankName',
  saveSalesInvoice: '/saveSalesInvoice',
  searchInvoice: '/searchInvoice',
  searchInvoiceApproval: '/searchInvoiceApproval',
  getInvoiceById: '/getInvoiceById',
  getInvoiceCancellationType: '/getInvoiceCancellationType',
  getInvoiceCancellationReason: '/getInvoiceCancellationReason',
  getInvoiceCancellationOtherReason: '/getInvoiceCancellationOtherReason',
  cancelInvoice: '/cancelInvoice',
  approveInvoice: '/approveInvoice',
  searchByInvoiceNumber: '/searchByInvoiceNumber',
  searchByChassisNumber: '/searchByChassisNumber',

  /* ------------- Exchange Inventory ----------- */
  exchangeInventory: '/exchangeInventory',
  updateExchangeInventory: '/updateExchangeInventory',
  module :'salesandpresales',
  exchangeInventroyController:'exchangeInventory',

  /* ------------- Product ----------- */
  getVariantBySubModel: '/getVariantBySubModel',

  /*-----Feedback------*/

  addFeedbackForm: '/addFeedbackForm',
  dealerMaster: '/dealerMaster',
  getPincodeDetail: '/getPincodeDetail',
  getDealerRegionInfo: '/getDealerRegionInfo',
  autoCompleteTehsilCityPincode: '/autoCompleteTehsilCityPincode'

}