
import { UploadableFile } from 'src/app/ui/file-upload/file-upload';
import { ViewPCRDomain, WarrantyPcrPhotos } from '../../product-concern-report/domain/product-concern-report.domain';

export interface Goodwilltype {
  goodwillType: string;
}
export interface PriceType {
  id: number;
  price: string;
}

/**
 * Submit Goodwill Interface
 */

export interface SubmitGoodwill {
  warrantyGoodwill: Goodwill;
  multipartFileList: UploadableFile[];
}

export interface Goodwill {
  goodwillType: string;
  goodwillReason: string;
  dealerRemark: string;
  kaiRemark: string;
  draftFlag: boolean;
  budgetConsumed:number
  warrantyPcr: Warranty;
  sparePartRequisitionItem?: SparePartRequisitionItem[];
  labourCharge?: LabourList[];
  outsideJobCharge?: OutsideChargeList[];  
    
}
export interface LabourList {
    labourChargeId: number;
    goodwillAmount: number;
}
export interface OutsideChargeList {
    jobcodeId: number;
    goodwillAmount: number;
}
export interface SparePartRequisitionItem {
  id: number;
  gwClaimQuantity?:number;
  gwClaimApprovedQuantity?: number;
  gwClaimApprovedAmount?: number;
  gwApprovedPercent?: number;
  warrantyMtPartFailureCode?: Warranty;
  priceType?: string;
  // approvedQuantity: number;
}

export interface Warranty {
  id: number;
}

/**
 * Goodwill Search
 */

export interface GoodwillSearch {
  page: number;
  size: number;
  goodwillNo: string;
  pcrNo: string;
  jobCardNo: string;
  goodwillType: string;
  goodwillFromDate: string;
  goodwillToDate: string;
  machineModel:string,
  jobCardFromDate: string;
  jobCardToDate: string;
  failureType:String;
  mobileNo:string;
  registrationNo:string;
  chassisNo:String;
  status: string;
  dealerShip:any
  dealerId:number
  branch:number
  state:number
}

export interface GoodwillList {
  goodwillNo: string;
  pcrNo: string;
  jobCardNo: string;
  goodwillType: string;
  goodwillDate: string;
  status: string;
  chassiNo:string;
  model:string;
}

/**
 * GoodWill View
 */

// Generated by https://quicktype.io

export interface GoodwillViewMain {
  goodwillViewDto: GoodwillView;
  warrantyPart: WarrantyPartGoodwill[];
  labourCharge: LabourCharge[];
  outSideLabourCharge: OutSideCharge[]   
  approvalDetails?:any[]
}

export interface ApproveQuantity {
    kaiRemarks: string;
    approvalStatus : string;  
    budgetConsumed : number;
    approvalParts: ApprovalParts[];
    approvalLabours : ApprovalLabourORCharges[];
    approvalOutsideCharges : ApprovalLabourORCharges[];
    warrantyGwlId: number;
  }
export interface ApprovalParts {
    approvedQuantity: number;
    gwApprovedPercent:number;
    id: number;
    priceType:string
  }
  export interface ApprovalLabourORCharges {
      approvedAmount: number;
      id: number;
    }
  
export interface GoodwillView {
  goodwillNo: string;
  warrantyPcr: ViewPCRDomain;
  goodwillDate: null;
  goodwillType: string;
  goodwillReason: string;
  dealerRemark: string;
  kaiRemark: string;
  status: null;
  id: number;
  budgetConsumed?:number;
  wcrNo?:string;
  warrantyGoodwillPhoto: WarrantyPcrPhotos[];
  createWcr?:boolean
}

// export interface WarrantyPcr {
//   serviceJobCard: ServiceJobCard;
//   pcrNo: string;
//   failureType: string;
//   kaiRemarks: string;
//   dealerRemarks: string;
//   soilType: string;
//   crop: string;
//   cropCondition: string;
//   fieldCondition: string;
//   pcrDate: string;
//   dealerObservation: string;
//   actionTaken: string;
//   warrantyPcrImplements: WarrantyPcrImplement[];
//   status: string;
//   id: number;
//   repeatFailure: null;
//   noOfTimes: null;
// }

// export interface ServiceJobCard {
//   jobCardNo: string;
//   dealerMaster: ServiceJobCardDealerMaster;
//   customerMaster: CustomerMaster;
//   machineInventory: MachineInventory;
//   totalHour: number;
//   jobCardDate: string;
//   registrationNumber: null;
//   customerConcern: null;
//   mechanicObservation: null;
//   status: string;
//   id: number;
//   dateOfFailure: string;
// }

// export interface CustomerMaster {
//   lastName: string;
//   id: number;
//   mobileNo: string;
//   customerName: string;
//   address: string;
// }

// export interface ServiceJobCardDealerMaster {
//   id: number;
//   serviceDealer: string;
//   serviceDealerAddress: null;
// }

// export interface MachineInventory {
//   dealerMaster: MachineInventoryDealerMaster;
//   chassisNo: string;
//   engineNo: string;
//   registrationNumber: null;
//   machineMaster: MachineMaster;
//   id: number;
//   dateOfInstallation: null;
// }

// export interface MachineInventoryDealerMaster {
//   id: number;
//   soldToDealer: string;
// }

// export interface MachineMaster {
//   model: string;
//   id: number;
// }

// export interface WarrantyPcrImplement {
//   id: number;
//   implementCategory: string;
//   implement: string;
//   implementMake: string;
//   implementSerialNumber: string;
//   gearRatio: string;
//   engineRpm: number;
//   percentOfUsage: number;
//   usageFailure: boolean;
// }

export interface WarrantyPartGoodwill {
  unitPrice: number;
  gwClaimApprovedQuantity: number;
  gwClaimQuantity: number;
  description: string;
  partNo: string;
  reqQuantity: number;
  id: number;
  sparePartMasterId: number;
  gwClaimApprovedAmount: number;
  gwApprovedPercent?: number;
  approvedQuantity: number;
  rejectedQuantity?:number
  complaintDescription: string;
  code: string;
  failureId: number;
  sparePartRequisitionId: number;
  claimQuantity: number;
  priceType: string;
}

export interface LabourCharge {
    
    labourChargeId:number,
    labourCode:string,
    labourDesc:string,
    labourHour:string,
    claimAmount?:number,
    pcrAmount?:number,
    approvedAmount?:number,
    acceptedPercentage?:number,
    goodwillApprovedAmount?:number,     
    goodwillClaimAmount?:number,
    rejectedAmount?:number        
}

export interface OutSideCharge {
    jobcode:string,
    jobcodeId:number,
    jobcodeDesc:string,
    pcrAmount?:number,
    claimAmount?:number,
    approvedAmount?:number,
    acceptedPercentage?:number,
    goodwillApprovedAmount?:number,     
    goodwillClaimAmount?:number,
    rejectedAmount?:number
}