export interface WarrantyDeliveryChallan {
  hsnCode: string;
  quantity: number;
  unitPrice: number;
  wcrNo: string;
  pcrId: number;
  jobCardId: number;
  itemNo: string;
  value: number;
  gstAmount: number;
  gstPercent: number;
  totalAmount: number;
  wcrId: number;
  itemDescription: string;
  sparePartRequisitionItemId: number;
  sparePartMasterId: number;
  isSelect?: boolean;
  sparePartMaster?: SparePartMaster;
  id?: number;
  dcNo?: string;
  transporterName?: string;
  dcDate?: string;
  docketNumber?: string;
  numberOfBox?: number;
  dispatchDate?: string;
}

export interface WpdcSubmit {
  sparePartRequisitionItem: SparePartRequisitionItem[];
  transporterName: string;
  docketNumber: string;
  dispatchDate: string;
  numberOfBox: string;
  draftFlag: boolean;
}

export interface SparePartRequisitionItem {
  id: number;
  sparePartMaster: SparePartMaster;
  gstPercent: number;
  gstAmount: number;
  totalAmount: number;
  hsnCode: string;
}

export interface SparePartMaster {
  id: number;
  itemNo: string;
}

export interface WpdcSearch {
  page: number;
  size: number;
  dcFromDate: string;
  dcNo: string;
  dcToDate: string;
  machineModel: string;
  wcrFromDate: string;
  wcrNo: string;
  wcrToDate: string;
}

export interface WpdcList {
  dealerEmail: string;
  dcDate: string;
  docketNumber: string;
  dealer_code: string;
  numberOfBox: string;
  transporter_name: string;
  dispatchDate: string;
  dealerName: string;
  dcNo: string;
}
export interface WpdcViewMaster {
  warrantyDeliveryChallanViewDto: WpdcView;
  dealerMaster : DealerMaster;
  warrantyPart: SparePartRequisitionItem[];
}
export interface WpdcView {
  dcNo: string;
  // sparePartRequisitionItem: SparePartRequisitionItem[];
  transporterName: string;
  dcDate: string;
  docketNumber: string;
  numberOfBox: number;
  dispatchDate: string;
  id: number;
}

export interface DealerMaster {
  emailId: string;
  mobileNo: string;
  dealerCode: string;
  id: number;
  serviceDealerAddress: string;
  serviceDealer: string;
}
export interface SparePartRequisitionItem {
  gstPercent: number;
  // sparePartMaster: SparePartMaster;
  gstAmount: number;
  totalAmount: number;
  approvedQuantity: number;
  priceUnit: number;
  amount: number;
  warrantyWcr: WarrantyWcr;
  id: number;
  partNo: string;
  description: string;
  wcrNo: string;
}

// export interface SparePartMaster {
//   igstPercent: number;
//   spmrp: number;
//   id: number;
//   partNo: string;
//   description: string;
// }

export interface WarrantyWcr {
  wcrNo: string;
  id: any;
}
export interface WarrantyWcrs {
  wrId: WarrantyWcr;
}

// Generated by https://quicktype.io

export interface WpdcJSON {
  draftFlag: boolean;
  transporterName: string;
  docketNumber: string;
  numberOfBox: number;
  dispatchDate: string;
  warrantyWcr?: WarrantyWcr[];
  id: number;
}

export interface WarrantyWcr {
  id: any;
  // warrantyPcr: WarrantyPcr;
}

// export interface WarrantyPcr {
//   id:             number;
//   serviceJobCard: ServiceJobCard;
// }

// export interface ServiceJobCard {
//   id:                       number;
//   sparePartRequisitionItem: SparePartRequisitionItem[];
// }

// export interface SparePartRequisitionItem {
//   id:              number;
//   sparePartMaster: SparePartMaster;
//   gstPercent:      number;
//   gstAmount:       number;
//   totalAmount:     number;
//   hsnCode:         string;
// }

// export interface SparePartMaster {
//   id:     number;
//   itemNo: string;
// }
