package com.i4o.dms.kubota.common.service;

import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.util.HashMap;

import org.springframework.stereotype.Service;

import com.i4o.dms.kubota.connection.ConnectionConfigurationImpl;
import com.itextpdf.text.pdf.PdfWriter;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.HtmlExporter;
import net.sf.jasperreports.engine.export.JRCsvExporter;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleHtmlExporterOutput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.export.SimplePdfExporterConfiguration;
import net.sf.jasperreports.export.SimpleWriterExporterOutput;
import net.sf.jasperreports.export.SimpleXlsReportConfiguration;
import net.sf.jasperreports.export.SimpleXlsxReportConfiguration;
import net.sf.jasperreports.engine.export.JRXlsExporter;
import net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter;

@Service
public class JasperPrintService extends ConnectionConfigurationImpl {
	
	/**
     * @author Suraj_Gaur
     * @apiNote This the PDF and Excel file generator method by using JASPER library.
     * @param jasperFile - This include two things the request realpath and followed by Jasper file name. 
     * 		  Eg: fileName= "ExportPartDumpList.jasper"; 
     * 	          jasperFile = request.getRealPath("/WEB-INF/reports/"+ fileName);
     * @param jasperParameter - It include all parementers that need as input in SQL Procedure file executing it.
     * @return JasperPrint
     */
	public JasperPrint getJasperPrint(String jasperFile, HashMap<String, Object> jasperParameter)
	{
		JasperPrint jasperPrint = null;
		Connection connection = null;
		
		try {
			connection = getConnection();
			if (connection != null) {
				jasperPrint = JasperFillManager.fillReport(jasperFile, jasperParameter, connection);
			}
		} catch (Exception e) {
			System.out.println("Message Error: " + e.getMessage());
			jasperPrint = null;
			e.printStackTrace();
		}
		finally {
			try {
				if (connection != null)
					connection.close();
			} catch (Exception e) {
				jasperPrint = null;
				e.printStackTrace();
			}
		}
		return jasperPrint;
	}

	/**
	 * @author Suraj_Gaur
	 * @apiNote This is the method for giving output stream as PDF of generated JASPER file.
	 * @param jasperPrint
	 * @param printStatus
	 * @param outputStream
	 * @throws Exception
	 */
    public void printPdfReport(JasperPrint jasperPrint, String printStatus, OutputStream outputStream) 
    		throws Exception
    {
	    JRPdfExporter exporter = new JRPdfExporter();	//for PDF report
	   
	    exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
		exporter.setExporterOutput(new SimpleOutputStreamExporterOutput(outputStream));
		
	    SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
		if(printStatus != null && printStatus.equals("true")){
	          configuration.setPermissions(PdfWriter.ALLOW_COPY | PdfWriter.ALLOW_PRINTING);
	          configuration.setPdfJavaScript("this.print();");
		}
		
        exporter.setConfiguration(configuration);
		exporter.exportReport();
	}
    
    
    
    /**
     * @author suraj.gaur
     * @apiNote This is the method for giving output stream as JRXls Excel of generated JASPER file.
     * @param jasperPrint - THis is the Jasper print file generated by Jasper Library
     * @param fileName - The name of the Jasper file that used to print the excel file. 
     * 		  Eg: fileName= "ExportPartDumpList.jasper"
     * @param sheetName - This is the sheets name array
     * 		  Eg: String sheetName[] = { "PART_DUMP_LIST" };
     * @throws JRException
     * @throws IOException
     */
	public void printExcelReport(JasperPrint jasperPrint, String fileName, String sheetName[], OutputStream outputStream) 
			throws JRException, IOException 
	{
		/*
		String filePath = messageSource.getMessage("vecv.dumplist.file.path", new Object[] {},
				LocaleContextHolder.getLocale());
	
		File file = new File(filePath);
		if (file.exists() == false) {
			file.mkdirs();
		}
		
		File f1 = new File(filePath + "\\" + fileName.substring(0,fileName.indexOf(".")) + ".xls");
		OutputStream fileoutputStream = new FileOutputStream(f1);
		*/
		
		jasperPrint.setProperty("net.sf.jasperreports.export.xls.ignore.graphics", "true");
		
		JRXlsExporter xlsExporter = new JRXlsExporter();
		
		xlsExporter.setExporterInput(new SimpleExporterInput(jasperPrint));
		xlsExporter.setExporterOutput(new SimpleOutputStreamExporterOutput(outputStream));
		//xlsExporter.setExporterOutput(new SimpleOutputStreamExporterOutput(fileoutputStream));
		
		SimpleXlsReportConfiguration configuration = new SimpleXlsReportConfiguration();
		configuration.setSheetNames(sheetName);
		/*
		 * configuration.setOnePagePerSheet(true);
		 * configuration.setDetectCellType(true);
		 * configuration.setCollapseRowSpan(false);
		 * configuration.setWhitePageBackground(false);
		 * configuration.setRemoveEmptySpaceBetweenColumns(true);
		 * configuration.setRemoveEmptySpaceBetweenRows(true);
		 * configuration.setIgnorePageMargins(true);
		 */
		
		xlsExporter.setConfiguration(configuration);
		xlsExporter.exportReport();
		/*
		System.out.println("Printed PARTDUMPLIST Report");
		fileoutputStream.flush();
		fileoutputStream.close();
		*/
	}
	
	/**
     * @author suraj.gaur
     * @apiNote This is the method for giving output stream as JRXlsx Excel of generated JASPER file.
     * @param jasperPrint - This is the Jasper print file generated by Jasper Library
     * @param sheetName - This is the sheets name array
     * 		  Eg: String sheetName[] = { "PART_DUMP_LIST" };
     * @throws JRException
     * @throws IOException
     */
	public void exportToXlsx(JasperPrint jasperPrint, String sheetName[], OutputStream outputStream) throws JRException 
	{
		JRXlsxExporter exporter = new JRXlsxExporter();
		
		exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
		exporter.setExporterOutput(new SimpleOutputStreamExporterOutput(outputStream));
		
		SimpleXlsxReportConfiguration reportConfig = new SimpleXlsxReportConfiguration();
		
		reportConfig.setSheetNames(sheetName);
		exporter.setConfiguration(reportConfig);
		
		exporter.exportReport();
	}

	/**
     * @author suraj.gaur
     * @apiNote This is the method for giving output stream as CSV of generated JASPER file.
     * @param jasperPrint - THis is the Jasper print file generated by Jasper Library
     * @param fileName - The name of the Jasper file that used to print the excel file. 
     * 		  Eg: fileName= "ExportPartDumpList.jasper"
     * @param sheetName - This is the sheets name array
     * 		  Eg: String sheetName[] = { "PART_DUMP_LIST" };
     * @throws JRException
     * @throws IOException
     */
	public void exportToCsv(JasperPrint jasperPrint, String fileName, OutputStream outputStream) throws JRException 
	{
		JRCsvExporter exporter = new JRCsvExporter();
		
		exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
		exporter.setExporterOutput(new SimpleWriterExporterOutput(outputStream));
		
		exporter.exportReport();
	}

	/**
     * @author suraj.gaur
     * @apiNote This is the method for giving output stream as HTML of generated JASPER file.
     * @param jasperPrint - THis is the Jasper print file generated by Jasper Library
     * @param fileName - The name of the Jasper file that used to print the excel file. 
     * 		  Eg: fileName= "ExportPartDumpList.jasper"
     * @param sheetName - This is the sheets name array
     * 		  Eg: String sheetName[] = { "PART_DUMP_LIST" };
     * @throws JRException
     * @throws IOException
     */
	public void exportToHtml(JasperPrint jasperPrint, String fileName, OutputStream outputStream) throws JRException 
	{
		HtmlExporter exporter = new HtmlExporter();
		
		exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
		exporter.setExporterOutput(new SimpleHtmlExporterOutput(outputStream));
		
		exporter.exportReport();
	}
    
}
